### ISSUE TITLE
Input file styles

### ISSUE THREAD

**Issue by robhaswell** [AwjTay/5-a-side-app#6]
My recommendation, make these changes:

```css
.input_field {
  padding: 0.5rem;
  margin: 1rem;
  font-size: 1.2rem;
}
```
